import {
  LocateFixed,
  StepForward,
  FoldHorizontal,
  Crosshair,
  Plane,
  Bot,
  Wind,
  Mouse,
  TrendingUp,
  Radio,
  Swords,
  Crown,
  Zap,
  Rocket,
  PocketKnife,
  ArrowRightLeft,
  Flag,
  BowArrow,
  Bomb,
  Scale,
} from "lucide-react";

export const MILESTONES = [
  {
    key: "bigBattle",
    label: "Big Battle",
    icon: Swords,
    color: "--color-combat",
    weight: 2,
    description: "Sharp simulteous declines in army value for both teams.",
  },
  {
    key: "comeback",
    label: "Comeback",
    icon: TrendingUp,
    color: "--color-eco",
    weight: 3,
    description: "Winning team once 50% behind in army value.",
  },
  {
    key: "backAndForth",
    label: "Back and Forth",
    icon: ArrowRightLeft,
    color: "--color-eco",
    weight: 2,
    description: "Constant momentum shifts throught the battle.",
  },
  {
    key: "stomp",
    label: "Stomp",
    icon: Crown,
    color: "--color-upset",
    weight: -2,
    description: "Heavily one-sided, reduces spectator score.",
  },
  {
    key: "quickForfeit",
    label: "Quick Forfeit",
    icon: Flag,
    color: "--color-upset",
    weight: -2,
    description:
      "Premature forfeits reduce spectator score, weighted more for large teams.",
  },
  //{
  //  key: "baseRace",
  //  label: "Base Race",
  //  icon: Swords,
  //  color: "--color-combat",
  //  weight: 2,
  //  description: "Huge building damage for both teams relative to match size.",
  //},
  {
    key: "guerillaFighters",
    label: "Guerilla Fighters",
    icon: BowArrow,
    color: "--color-combat",
    weight: 3,
    description: "High average damage per metal spent. Combat efficient.",
  },
  {
    key: "carpalTunnel",
    label: "Carpal Tunnel",
    icon: Mouse,
    color: "--color-eco",
    weight: 2,
    description: "High average player APM throughout the game.",
  },
  {
    key: "windyDay",
    label: "Windy Day",
    icon: Wind,
    color: "--color-close",
    weight: 0,
    description: "Wind speed higher than average for the map, worth no points.",
  },
  {
    key: "spaceRace",
    label: "Space Race",
    icon: Rocket,
    color: "--color-close",
    weight: 2,
    description: "Close eco between teams throughout the match.",
  },
  {
    key: "legionMatch",
    label: "Legion Match",
    icon: Bot,
    color: "--color-eco",
    weight: 0,
    description: "Legion faction detected in this game, worth no points.",
  },
  {
    key: "earlyBombing",
    label: "Early Bombing",
    icon: Plane,
    color: "--color-combat",
    weight: 2,
    description: "At least 5 bomber built before 10 minutes.",
  },
  {
    key: "nailBiter",
    label: "Last Commander",
    icon: LocateFixed,
    color: "--color-close",
    weight: 3,
    description: "One commander left on winning team.",
  },
  {
    key: "afusRush",
    label: "AFUS Rush",
    icon: Zap,
    color: "--color-eco",
    weight: 1,
    description:
      "AFUS built relatively fast (e.g., 12 mins on 15 average wind speed), exclude metal maps.",
  },
  {
    key: "nukeRush",
    label: "Nuke Rush",
    icon: Bomb,
    color: "--color-combat",
    weight: 2,
    description:
      "Nuke built relatively fast (e.g., 12 mins on 15 average wind speed), exclude metal maps.",
  },
  {
    key: "orbitalCannons",
    label: "Big Guns",
    icon: Crosshair,
    color: "--color-combat",
    weight: 1,
    description: "Ragnarok/Calamity/Starfall is built",
  },
  {
    key: "techSpread",
    label: "Tech Spread",
    icon: PocketKnife,
    color: "--color-close",
    weight: 4,
    description:
      "Unit type diversity (bots, veh, air, sea, hov, amphib), weighted less for large games. Some units (commandos, bedbugs, spy bots) worth more.",
  },
  {
    key: "goliathDuel",
    label: "Goliath Duel",
    icon: FoldHorizontal,
    color: "--color-combat",
    weight: 5,
    description: "Both sides build experimental gantry built in a duel.",
  },
  {
    key: "commanderAttack",
    label: "Commander Attack",
    icon: StepForward,
    color: "--color-combat",
    weight: 3,
    description: "One team's commander moves into enemy start location.",
  },
  {
    key: "upset",
    label: "Imbalanced",
    icon: Scale,
    color: "--color-upset",
    weight: 0,
    description:
      "Noticable skill gap between teams regardless of outcome, worth no points.",
  },
];
